[build]
  publish = "public"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  directory = "build"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 