[build]
  publish = "public"

[dev]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/express-mcp-server"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/oauth-authorization-server"
  to = "/.netlify/functions/express-mcp-server"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/oauth-protected-resource"
  to = "/.netlify/functions/express-mcp-server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200