[build]
  publish = "public"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "accept, content-type, referer, sec-ch-ua, sec-ch-ua-mobile, sec-ch-ua-platform, user-agent"
    Access-Control-Max-Age = "86400"
    Access-Control-Expose-Headers = "content-type"

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/index"
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE"]

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/index"
  status = 204
  force = true
  methods = ["OPTIONS"]
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "accept, content-type, referer, sec-ch-ua, sec-ch-ua-mobile, sec-ch-ua-platform, user-agent"
    Access-Control-Max-Age = "86400"
    Access-Control-Expose-Headers = "content-type"
  